[build]
builder = "DOCKERFILE"
buildArgs = ["REACT_APP_API_URL=https://posdashboard-production.up.railway.app"]

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
processType = "web"
numReplicas = 1 